### ISSUE TITLE
Merge buildtools into the Paddle repo

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/buildtools#11]
While reviewing https://github.com/PaddlePaddle/buildtools/pull/10, I noticed that we need a document, currently `buildtools/README.md`, to explain the building of PaddlePaddle to follow the manylinux standard.  It is inconvenient to integrate documents out of the Paddle, book, and models repos to our official Web site paddlepaddle.org.  And it doesn't make sense to add buildtools as an additional repo from which paddlepaddle.org picks documents.  An additional reason to merge buildtools into Paddle is that the building tools for releasing should be the same used in development, so could we verify the building process during development.

**Comment by typhoonzero** [comment]
PS: buildtools docker images takes about 1 hours to build, and it's too large (2 GB after compress),  so we might not need to update `Dockerfile` under PaddlePaddle repo.

**Comment by wangkuiyi** [comment]
I agree and let us keep buildtools from the Dockerfile in the root directory of Paddle repo.  Also, I suggest to rename buildtools into manylinux.
