### ISSUE TITLE
Move Dockerfile.android from repo Paddle to buildtools

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/buildtools#2]
According to the discussion [here](https://github.com/PaddlePaddle/Paddle/issues/4050#issuecomment-342375119), let us move [Dockerfile.android](https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile.android) to this repo, so could we monitor and make sure that the content of Dockerfile doesn't depend on the versioning of Paddle.

**Comment by typhoonzero** [comment]
Sure, will do.

**Comment by wangkuiyi** [comment]
Actually, I think we might need to merge buildtools into the Paddle repo instead.  For the reason, please look as https://github.com/PaddlePaddle/buildtools/issues/11.
