### ISSUE TITLE
build_all.sh is not used?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/buildtools#3]
It seems that the [Dockerfile.x86_64](https://github.com/PaddlePaddle/buildtools/blob/master/manylinux/Dockerfile-x86_64) doesn't use the `build_all.sh`.  Is this file required or could be removed?

**Comment by typhoonzero** [comment]
`build_all.sh` use `Dockerfile.x86_64` to build development images for different cuda+cudnn versions. Will update `README.md` for instructions.

**Comment by wangkuiyi** [comment]
I see the relationship between the build_all.sh and Dockerfile now. Thanks!
